version: '3.8'
services:
  dev-db:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: gymApp
    networks:
      - gymApp
  test-db:
    image: postgres:13.2
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: gymApp
    networks:
      - gymApp
networks:
  gymApp: